#!/usr/bin/env python
###############################################################
# Python version of the idascript utility for IDA.
#
# Original idascript utility: http://www.hexblog.com/?p=128
#
# Craig Heffner
# 14-November-2012
# http://www.tacnetsol.com
# http://www.devttys0.com
###############################################################

import os
import pty
import select
import subprocess
import sys
import tempfile
import threading

idc_args = ['__idascript_active__']
IDA_INSTALL_PATH = "/Applications/IDA Pro 6.5/IDA binaries/"
OUTFILE = os.path.join(tempfile.gettempdir(), 'ida_script_stdout.txt')

# Check usage
if len(sys.argv) < 2:
	print ""
	print "Usage: %s [--64bit] <target file> <ida script file> [script arguments]" % os.path.basename(sys.argv[0])
	print ""
	sys.exit(1)

# Always use the 64-bit version of IDA if it was explicitly specified
if sys.argv[1] == '--64bit':
	suffix = '64'
	sys.argv.pop(1)
else:
	suffix = ''

# Get IDB / script file from command line
if len(sys.argv) >= 3:
	idb = os.path.abspath(sys.argv[1])
	idc = os.path.abspath(sys.argv[2])
	idc_args += sys.argv[3:]
	
	if idb.endswith('.i64'):
		suffix = '64'
else:
	idc = os.path.abspath(sys.argv[1])
	idb = "-t"
	idc_args += sys.argv[2:]

# Use the right IDA executable for the right platform
if sys.platform == 'win32':
	ida = 'idaw' + suffix
else:
	ida = 'idal' + suffix

# Windows has a .exe file extension
if sys.platform == 'win32':
	ida += '.exe'

with open(OUTFILE, 'wb'):
    pass

def threaded(func):
    def wrapper(*args, **kwargs):
        thread = threading.Thread(target=func, args=args, kwargs=kwargs)
        thread.daemon = True
        thread.start()
    return wrapper

@threaded
def tail(path):
    subprocess.call(['tail', '-f', path])

@threaded
def print_file(f):
    while True:
        if select.select([f], [], [], 0.1)[0]:
            data = f.read(1)
            sys.stdout.write(data)

# Deal with I/O
master, slave = pty.openpty()

tail(OUTFILE)
print_file(os.fdopen(master, 'rb'))

# Run IDA
p = subprocess.Popen([os.path.join(IDA_INSTALL_PATH, ida), '-A', '-S' + idc + ' ' + ' '.join(idc_args), idb], stdout=slave)
p.communicate('')

# Display contents of output file, then clean up
if os.path.exists(OUTFILE):
	# sys.stdout.write(open(OUTFILE, 'rb').read())
	os.unlink(OUTFILE)
